# Generated by Django 5.0.7 on 2025-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_contact_number', models.CharField(max_length=15)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_address', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_contact_number', models.CharField(max_length=15)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.TextField()),
                ('item_description', models.TextField()),
                ('number_of_items', models.PositiveIntegerField(default=1)),
                ('parcel_colour', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('date_sent', models.DateField()),
                ('estimated_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Returned', 'Returned'), ('Failed Delivery', 'Failed Delivery')], default='Pending', max_length=50)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
