# Generated by Django 5.0.7 on 2025-02-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_courier_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to=settings.AUTH_USER_MODEL),
        ),
    ]
