# Generated by Django 5.0.7 on 2025-02-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_category', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], help_text='Select the destination category (e.g., Domestic or International)', max_length=100)),
                ('weight_min', models.DecimalField(decimal_places=2, help_text='Minimum weight (kg) for this rate', max_digits=6)),
                ('weight_max', models.DecimalField(decimal_places=2, help_text='Maximum weight (kg) for this rate', max_digits=6)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base fee for shipments in this weight range', max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Additional fee per kilogram above the minimum weight', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='courier',
        ),
        migrations.AddField(
            model_name='courier',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', help_text='Select the delivery category', max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the package weight in kilograms', max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
