# Generated by Django 5.0.7 on 2025-02-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_courier_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Rate for the shipment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='receiver_city',
            field=models.CharField(blank=True, default='GAMB. 21', help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='receiver_country',
            field=models.CharField(default='Italy', max_length=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='receiver_state',
            field=models.CharField(blank=True, default='GAMB. 34', help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='receiver_street',
            field=models.CharField(blank=True, default='ABO. NAG, 23', help_text='Street', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='receiver_zip',
            field=models.CharField(blank=True, default='90030', help_text='Zip Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='scac',
            field=models.CharField(blank=True, default='N/A', help_text='Standard Carrier Alpha Code (SCAC)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='seal_number',
            field=models.CharField(default='9977', help_text='Seal Number', max_length=50),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_city',
            field=models.CharField(blank=True, default='N/A', help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_co',
            field=models.CharField(blank=True, default='N/A', help_text='C/O (if applicable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_country',
            field=models.CharField(default='Australia', max_length=100),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_state',
            field=models.CharField(blank=True, default='N/A', help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_street',
            field=models.CharField(blank=True, default='N/A', help_text='Street', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='sender_zip',
            field=models.CharField(blank=True, default='N/A', help_text='Zip Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='trailer_number',
            field=models.CharField(default='332764', help_text='Trailer Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='courier',
            name='receiver_address',
            field=models.TextField(default='VIA 36 ASILLE ITAY', help_text='Full address line'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='receiver_name',
            field=models.CharField(default='SANA CISERLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='courier',
            name='sender_address',
            field=models.TextField(default='No Return Address', help_text='Full address line'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='sender_contact_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='courier',
            name='sender_name',
            field=models.CharField(default='Horacio Roscinto', max_length=255),
        ),
    ]
