# Generated by Django 5.0.7 on 2025-02-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_courier_rate_courier_receiver_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='sender_co',
        ),
    ]
